language: node_js
node_js: 6
sudo: false
dist: trusty
cache:
  yarn: true
  pip: true

env:
  global:
  - JOBS=5
  - DOCKER_COMPOSE_METHOD=build

install:
  - yarn install --non-interactive
  - ember sauce:connect

script:
  - ember test --config-file testem.sauce.js --test-port 7000

after_script:
  - ember sauce:disconnect

before_deploy:
  - pip install --user -I
      python-openstackclient
      python-heatclient
      python-keystoneclient &>> /dev/null

deploy:

 - provider: script
   script: DEPLOY_ENV=dev bash extras/openstack_deploy.sh
   on:
     branch: master

 - provider: script
   script: DEPLOY_ENV=test bash extras/openstack_deploy.sh
   on:
     tags: true

notifications:
  slack:
    secure: YLn916ZEAUDziD3G88jfNhiNwb2clh8ieNOo8AW+kF1mS4MKd9/fKW3zOUUgQdkv4khG4zBCqHX1PXANaqYj07wGre/zeZeUBwvvIlbesyNxg6nGOxkMpsWJFPj78DQZh+yFwbrQ9CiP9E2MYu3MTD9hjYfXjeO5mk753mFR3Vvh4BAndifY6Ng9clL1b/pvds+K1tWHiXY052se8Ch/yLb+6VhngZ9C9qlFpKdKHdinay8xF1FFucwcsqGUtCrBLXW8pfZ1CzwFfthAA5/om2jW/1IpqzoPGJUF58GA6VVlgHs3GUTcH6uYiOgOd6jcKJVxz0B0EvujtD2jF/JBX9jrudlo5nv3PsIoqbfEBNWEdJ+v+cuExH3ny6N1+5PJwhb8sJWVBx9r6EbD9r7VRD1vW7jW19zesaPfbC4HaRZ5/NZ5rWkYqZrgJhEBkXOrcoPjxriq9RF7+OsBJ6Zt8wGDHhGuqp4hNN1QR8XbPWzQcQ47UAxfgoS0FUA0Gl6iWzgCT8Axu3joRRRVHE86+UUnjWattQMNajB4w2PulqZNdQWxdHxnjPyDuvwROxENXOzrVcu0lSuoo0+6Hky97BOSJl4uhp2dxFsMZwGrTvTmDUDtBzyP7q9x86fst695atODPIv6St4B/qCFIzdOtm240y5Crk8NXGqWLGumATA=

