---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=5

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive
  - cd lib/gviz && yarn install --no-interactive && cd -

before_script:
  - ember sauce:connect

after_script:
  - ember sauce:disconnect

script:
  - ember test --config-file testem.sauce.js --test-port 7000

before_deploy:
  - |
      declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

      openssl aes-256-cbc \
       -K $encrypted_3f0d43c1617b_key \
       -iv $encrypted_3f0d43c1617b_iv \
       -in ".travis/github_deploy_key.enc" \
       -out "$SSH_FILE" -d
       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host *" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" \
              "  StrictHostKeyChecking no" \
              "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
deploy:
  provider: script
  script: ember deploy $DEPLOY_ENV
  skip_cleanup: true
  on:
    tags: true
    branch: master
